### PR TITLE
Fix/review content rating type + Enhancement/company comments

### LINKED ISSUE #9: Uncertain endpoint results
Apparently `rating` within a review can be both a number and a string.

@menno-ll has contacted KiyOh to get documentation regarding their endpoints and see what they describe as results.

_Comes from issue #6_

### PR DESCRIPTION
**Pull request by menno-ll**
Does multiple things:

1. Fixes #9 by casting the reviewcontent rating based on the reviewcontent type
2. adds functionality to get company comments to a review

### CODE REVIEW

File: src/JKetelaar/Kiyoh/Models/Review.php [hunk 1]
```diff
@@ -28,6 +28,11 @@ class Review
      */
     private $rating;
 
+    /**
+     * @var string
+     */
+    private $comments;
```
Comment (JKetelaar) [inline src/JKetelaar/Kiyoh/Models/Review.php]: If it is a single string, is the plural form of `comment` the right word to use? Do you have an example to clear this up for me

File: src/JKetelaar/Kiyoh/Models/ReviewContent.php [hunk 2]
```diff
@@ -82,18 +82,48 @@ public function setType(string $type): void
...
+    public function getRating()
     {
-        return $this->rating;
+        $rating = $this->rating;
+        switch ($this->getType()) {
+            case 'INT':
+                $rating = intval($rating);
+                break;
+            case 'BOOLEAN':
+                if ($rating === 'true') {
```
Comment (JKetelaar) [inline src/JKetelaar/Kiyoh/Models/ReviewContent.php]: What about:
```
$rating = filter_var($rating, FILTER_VALIDATE_BOOLEAN);
```

**Comment by JKetelaar** [comment]
Great change, thank you so much!

File: src/JKetelaar/Kiyoh/Models/Review.php (hunk 1 above)
Comment (mentosmenno2) [reply src/JKetelaar/Kiyoh/Models/Review.php]: Will respond from my private git account this time, as I'm not at work, so don't get confused :).

It's a comment from the company on the review.
Something like the screenshot below. ( it's the multiline text below "reactie van het bedrijf").
It's a multiline text. I agree `comments` may not be the right word to use.
Maybe `companyComment` or otherwise indeed just `comment`, as it's just a comment to the review.

Screenshot_20191117-103607_Chrome

File: src/JKetelaar/Kiyoh/Models/ReviewContent.php (hunk 2 above)
Comment (mentosmenno2) [reply src/JKetelaar/Kiyoh/Models/ReviewContent.php]: Brilliant

**Comment by menno-ll** [comment]
Here you go :).
Couldn't resist to just fix it now instead of later.

File: src/JKetelaar/Kiyoh/Models/Review.php (hunk 1 above)
Comment (JKetelaar) [reply src/JKetelaar/Kiyoh/Models/Review.php]: Ahhh makes total sense, then the `comment` is the perfect naming. Thank you for elaborating. Could you add some docs to the `comment` getter, so this is also clear for future developers?

File: src/JKetelaar/Kiyoh/Models/Review.php [hunk 3]
```diff
@@ -129,6 +136,22 @@ public function setRating(float $rating): void
         $this->rating = $rating;
     }
 
+    /**
+     * @return string
```
Comment (JKetelaar) [inline src/JKetelaar/Kiyoh/Models/Review.php]: Could you add a line of extra information indicating what `comment` means and returns?

**Review by JKetelaar — CHANGES_REQUESTED** [review]

File: src/JKetelaar/Kiyoh/Models/Review.php (hunk 3 above)
Comment (menno-ll) [reply src/JKetelaar/Kiyoh/Models/Review.php]: Yes!

**Comment by JKetelaar** [comment]
Thanks again @menno-ll / @mentosmenno2!
